# Generated by Django 4.1.2 on 2022-10-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
