# Generated by Django 4.1.2 on 2022-10-13 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.RegexValidator("^\\d{1,10}$")],
            ),
        ),
    ]
