# Generated by Django 4.1.2 on 2022-10-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
